global:
  scrape_interval: 5s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot /actuator/prometheus
  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coffee-backend:8080']

  # Node Exporter (host mode)
  - job_name: 'node'
    static_configs:
      - targets: ['172.31.20.118:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['coffee_cadvisor:8080']
