global:
  scrape_interval: 5s

# üî• Quan tr·ªçng: external_url ƒë·ªÉ Prometheus ch·∫°y trong subpath
web:
  external_url: https://nhom2qtm.duckdns.org/prometheus

scrape_configs:

  # ==========================
  # PROMETHEUS ITSELF
  # ==========================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ==========================
  # SPRING BOOT BACKEND
  # ==========================
  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coffee-backend:8080']

  # ==========================
  # NODE EXPORTER (HOST MODE)
  # ==========================
  - job_name: 'node'
    static_configs:
      - targets: ['172.31.20.118:9100']

  # ==========================
  # CADVISOR (CONTAINER METRIC)
  # ==========================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['coffee_cadvisor:8080']
