global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['coffee_prometheus:9090']

  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coffee_backend:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['coffee_node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['coffee_cadvisor:8080']
